services:
  app:
    container_name: node_with_sqlserver_app
    build: .
    ports:
      - '3001:3000'
    environment:
      - DB_HOST=db
      - DB_USER=sa
      - DB_PASS=yourStrong(!)Password
      - DB_NAME=my_database
    depends_on:
      - db  # Ensures that the app only starts after the database service is ready

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest  # MSSQL Server image
    container_name: mssql_db
    ports:
      - "1433:1433"  # Expose default MSSQL port
    environment:
      - ACCEPT_EULA=Y  # Required to accept the SQL Server license terms
      - SA_PASSWORD=yourStrong(!)Password  # MSSQL Server admin password
      - MSSQL_DB=my_database  # Database name

volumes:
  db_data:  # Persistent storage for the database
    driver: local
